### ISSUE TITLE
Tool clobbers or strips comments and many HTML tags

### ISSUE THREAD

**Issue by ghost** [soffes/unmarkdown#2]
I got some use out of this tool, but had serious issues.

Input file:
```html
<!--One-line comment by itself-->

Line with an <!--inline comment--> inside

<!--
Block comment
-->

surrounding stuff
<!--
Block comment
-->
surrounding stuff

<expand-note>hello</expand-note>

<span class="spoiler">a secret</span>
```

Output:
```
Line with an inline comment inside


Block comment


surrounding stuff

Block comment

surrounding stuff

hello

a secret
```

(&lt;expand-note&gt; is a custom element I use on my site.)

**Comment by soffes** [comment]
You can see [in the readme](https://github.com/soffes/unmarkdown#supported-tags), only basic HTML tags are supported. I suppose it would be easy enough to add an option to preserve unknown HTML tags/comments.

I haven't worked on this (other than bumping dependencies for security reasons) in 6 years. Feel free to PR this feature if you'd like!

**Comment by yujiri8** [comment]
Oh, I read "For tags that aren't supported, their content will be added to the output" as meaning that the tags themselves would be preserved. Thanks for clarifying. Unfortunately I don't know Ruby :/

**Comment by soffes** [comment]
Oh true. I don't remember why I made project, but I was always fond of this silly library. I'll try to take a look if I have time.

**Comment by soffes** [comment]
Fixed in 0194be35dcb26381d48c9440222106234d0eade8

**Comment by soffes** [comment]
Version 0.2.0 is out with this fix. Enjoy :)

**Comment by ghost** [comment]
Wow, that was fast! Thank you :)
